<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2012-03-29 16:42

$extensionPath = t3lib_extMgm::extPath('pt_solr');
return array(
	'tx_ptsolr_controller_abstractactioncontroller' => $extensionPath . 'Classes/Controller/AbstractActionController.php',
	'tx_ptsolr_controller_breadcrumbscontroller' => $extensionPath . 'Classes/Controller/BreadCrumbsController.php',
	'tx_ptsolr_controller_facetfiltercontroller' => $extensionPath . 'Classes/Controller/FacetFilterController.php',
	'tx_ptsolr_controller_pagercontroller' => $extensionPath . 'Classes/Controller/PagerController.php',
	'tx_ptsolr_controller_quicksearchcontroller' => $extensionPath . 'Classes/Controller/QuickSearchController.php',
	'tx_ptsolr_controller_resultlistcontroller' => $extensionPath . 'Classes/Controller/ResultListController.php',
	'tx_ptsolr_controller_searchwordfiltercontroller' => $extensionPath . 'Classes/Controller/SearchWordFilterController.php',
	'tx_ptsolr_tests_basetestcase' => $extensionPath . 'Tests/BaseTestcase.php',
	'tx_ptsolr_tests_unit_controller_abstractactioncontrollertest' => $extensionPath . 'Tests/Unit/Controller/AbstractActionControllerTest.php',
	'tx_ptsolr_tests_unit_controller_abstractactioncontrollerimplementationmock' => $extensionPath . 'Tests/Unit/Controller/AbstractActionControllerTest.php',
	'tx_ptsolr_tasks_seleniumandpingtest' => $extensionPath . 'Classes/Tasks/SeleniumAndPingTest.php',
	'tx_ptsolr_tasks_addfields' => $extensionPath . 'Classes/Tasks/AddFields.php',
	'ux_tx_solr_fileindexer_file' => $extensionPath . 'Classes/XClasses/Ux_Tx_Solr_Fileindexer_File.php'
);